### ISSUE TITLE
listenTransfer is not working

### ISSUE THREAD

**Issue by zois** [allanclempe/ether-wallet-flutter#1]
Initially many many congrats on your work!
My issue is that in listenTransfer the events StreamSubscription gets bad, because of
`Unhandled exception: bad state: stream has already been listened to`
So although the transaction is completed ok, because I check it on etherscan, the app gets stuck in the processing loading indicator.
Any ideas?

Thanks!

**Comment by allanclempe** [comment]
Hi Zois, 

Thank you for your support. 

Could you post more information? Stack trace? Have you done any change to the source code?
I wrote that code a while ago, using web3dart v1.1.1, could you confirm if you're using exactly the same version? 
Something that you can try is to remove the ^ from the pubspec.yaml file to make sure that you're  using the same version. (web3dart: 1.1.1)

Besides, I will try to update their library to see if there's any issue. At that time, I didn't like the way they were handling events (compared to the original web3js), but might be better now. 

Thanks.

**Comment by zois** [comment]
I have updated the code in order to test in iOS. So pretty much I updated all the packages. I am using 1.2.1 version but I don't think this is the issue. 
Regarding the issue, probably I am stuck in the loading screen because I use a new account which has no coins, hence the Transfer event is never published from the contract :) 
However, there is a mishandling in the streams and the listening parts. It's very easy to reproduce. Just make a new transfer and put a breakpoint in contract_service.dart in the listenTransfer function. You will see that the variable "events" gets the bad state issue. 
Although I think if you use two accounts that have coins, this won't cause any issue? What do you think?

Thanks again,
Zois

**Comment by allanclempe** [comment]
Yep, that might be the problem. I've tried creating a new wallet from scratch, with no balance and I got stuck on transfer screen. It should display an error message ('out of gas'), but I will check what is happening there.
Send me your public address, I will send to you some tokens and ETH on ropsten network for you to test again.

Also, if you want to fork and send me your changes for iOS, I'd appreciate.

Thanks.

**Comment by zois** [comment]
I am working actually on a bitbucket repo for this. So send me your email to add you there.
I am also using my own smart contract which is deployed both on mainnet and ropsten and has more functions. So I am in a process of creating a wallet for it :)
My public address is 0x27b5bd35beb869d264aaa40f8da5714966435a8c.
I will close this now.
