### ISSUE TITLE
Realtime balance update

### ISSUE THREAD

**Issue by kaumudpa** [allanclempe/ether-wallet-flutter#25]
Hi,
Good job and amazing work with the project.

I want to know is there a way we can update the wallet balance without refreshing the page in realtime?

**Comment by allanclempe** [comment]
Thank you @kaumudpa 

Yes and it should be doing that already. You can [listen for events](https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#events) emitted by the contract

[check this](https://github.com/allanclempe/ether-wallet-flutter/blob/master/lib/context/wallet/wallet_handler.dart#L62)

**Comment by allanclempe** [comment]
closed due to inactivity, re-open if necessary.
