### ISSUE TITLE
Different address generated than official wallets

### ISSUE THREAD

**Issue by oliverbytes** [allanclempe/ether-wallet-flutter#27]
Why addresses generated from mnemonic seeds from this example is different from official wallets like Coinbase Wallet?

**Comment by allanclempe** [comment]
Hi @oliverbytes 

We had that question raised before, please check [this](https://github.com/allanclempe/ether-wallet-flutter/issues/7) out.
It could be 2 different things, `secret` used to generate the addresses and/or the `derive path`

Check if it solves your problem or more specific examples would be appreciated.

Thanks.

**Comment by allanclempe** [comment]
closed due to inactivity. re-open if necessary.
