### ISSUE TITLE
Invalid JSON RPC response

### ISSUE THREAD

**Issue by royacodes** [allanclempe/ether-wallet-flutter#28]
https://faucet.clempe.dev/ show below error when I want to transfer token

    Invalid JSON RPC response: "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 
    Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"

How can this problem be solved?

**Comment by allanclempe** [comment]
Just tried the 3 available networks and worked ok, could you try it again?

**Comment by royacodes** [comment]
> Just tried the 3 available networks and worked ok, could you try it again?

thank you, it's solved
