### ISSUE TITLE
Adding a simple ETH transaction

### ISSUE THREAD

**Issue by zois** [allanclempe/ether-wallet-flutter#3]
I am playing around with the web3dart lib, and what I 'd like to do is add a simple ETH transfer, without contract. I saw the way to do it here
https://github.com/simolus3/web3dart/blob/master/example/simple_transaction.dart
but I was wondering how we can actually use the way you are using in the contract related one, so as to have a loading page and listen to the transaction.
Can we actually do that? Because for the contract one, we emit an event Transfer so we listen to that. Do you know if Ethereum itself has a similar event so we can listen to and update the UI accordingly?
Any ideas?

Thanks again!

**Comment by allanclempe** [comment]
Hi Zois, 

Good question. Events in web3dart are associated to contracts. In web3js land has a way to subscribe events in the blockchain (https://web3js.readthedocs.io/en/v1.2.0/web3-eth-subscribe.html), as far as I know, web3dart doesn't.

It might be worth to ask them if there's any solution for that.

Alternatively, you could get the transaction hash and use a different API to check the transaction status. It's not ideal, but ..... Check out this API: https://blockexplorer.com/api-ref

Thanks.

**Comment by zois** [comment]
Thanks! What I will do, is actually ask for the receipt using getTransactionReceipt. If this is returned as null, then the transaction is still pending. It's not a subscription though, but a simple polling strategy will suffice I guess..
