### ISSUE TITLE
Transfer Money using Ethereum (Ropsten) Does not Work

### ISSUE THREAD

**Issue by csarigumba** [allanclempe/ether-wallet-flutter#30]
Hey Clempe, it seems the transfer money using Ropsten does not work. is there a bug in the latest commit?

**Comment by allanclempe** [comment]
Hi @csarigumba,

did run a test on my side and seems to be working ok, could you give me more details?
when you say transfer money, are you talking about [the faucet website](https://faucet.clempe.dev/) or through wallet?

**Comment by csarigumba** [comment]
Hey @allanclempe 👋

Actually, it works, I realized it just takes time. 
Anyway, closing this issue since there are no problems.
