### ISSUE TITLE
is it possible to create wallet avalanche avax  test network ??

### ISSUE THREAD

**Issue by xyzbilal** [allanclempe/ether-wallet-flutter#33]
Hi, first of all I m really thankful  that you shared this valuable work with us.
I m looking for some documents, works etc that I can create a wallet in avalanche test net, until now I could not find anything. 
My purpose is make app single point of contact that users interact contracts without needing any other solutions. 

if any Idea you can share, I will be so greatfull. Regards.

**Comment by xyzbilal** [comment]
Heeyy , I cant believe, I just added my contract info to Appconfig networks and it works like charm. its unbelivable. you are so greate man. thanks again. God bless you.

**Comment by allanclempe** [comment]
> Heeyy , I cant believe, I just added my contract info to Appconfig networks and it works like charm. its unbelivable. you are so greate man. thanks again. God bless you.

That's it mate = )
