### ISSUE TITLE
How to configure Firebase

### ISSUE THREAD

**Issue by advatar** [allanclempe/ether-wallet-flutter#4]
Got this: 

6.13.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
6.13.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.

**Comment by allanclempe** [comment]
I haven't setup the project for iOS but I have added GoogleServices-Info.plist file (as per commit above). just pull lastest and try again.

You might have some issues to get the QR code to work though, if so, please check [firebase_ml (iOS step)](https://pub.dev/packages/firebase_ml_vision)

**Comment by allanclempe** [comment]
@advatar please get latest and try again. Reopen if necessary. Thanks.
