### ISSUE TITLE
BIP39 gives different private key

### ISSUE THREAD

**Issue by zois** [allanclempe/ether-wallet-flutter#7]
Hello,

can you please explain below:
1. I create a new 12-word phrase from the app
2. I debug in order to get the private key
3. I use the exact 12 words in https://iancoleman.io/bip39/
4. I see that the entropy and BIP39 seed are exactly the same as the ones being created in the app
5. BUT... the private key generated by the above website is not the same as the one generated in the app, hence leading to a different address!

Specifically
```
@override
  String getPrivateKey(String mnemonic) { <-- entropy is also OK!
    String seed = bip39.mnemonicToSeedHex(mnemonic); <--OK!
    KeyData master = ED25519_HD_KEY.getMasterKeyFromSeed(seed); <-- I don't know about this
    final privateKey = HEX.encode(master.key); <--WRONG!
    print("private: $privateKey");
    return privateKey;
  }
```

So, why do we have this difference?
Is the address that is generated through the app the 1st address available (path m/44'/0'/0'/0/0) or is it sth else?

Thanks,
Zois

**Comment by allanclempe** [comment]
Short story: because Ethereum hdKey library is using a different secret compared to ED25519_HD_KEY.
[https://github.com/cryptocoinjs/hdkey/blob/master/lib/hdkey.js#L7](https://github.com/cryptocoinjs/hdkey/blob/master/lib/hdkey.js#L7)
[https://github.com/alepop/dart-ed25519-hd-key/blob/master/lib/src/base.dart#L15](https://github.com/alepop/dart-ed25519-hd-key/blob/master/lib/src/base.dart#L15)

Long story: I had to dig very deep to find out that, but here is the explanation: 

Here is the way you would generate the keys in JS using Ethereum library (possibly the same way the website site you mentioned is doing)

```javascript
const bip39 = require("bip39");
const hdkey = require("ethereumjs-wallet/hdkey");

async function generateAddressesFromSeed(seed, count) {
    const seedBuffer =await bip39.mnemonicToSeed(seed);
    let hdwallet = hdkey.fromMasterSeed(seedBuffer);
    const privateBuffer = await hdwallet.getWallet().getPrivateKey();
    const privateKey = privateBuffer.toString("hex"); // <-- this is what you looking for.

  let wallet_hdpath = "m/44'/60'/0'/0/"; // ETH path

  // derive accounts
  let accounts = [];
  for (let i = 0; i < count; i++) {
    let wallet = hdwallet.derivePath(wallet_hdpath + i).getWallet();
    let address = "0x" + wallet.getAddress().toString("hex");
    let privateKey = wallet.getPrivateKey().toString("hex");
    accounts.push({ address: address, privateKey: privateKey });
  }

  return {privateKey, accounts};
}

  generateAddressesFromSeed(
    "thought empty modify achieve arch tooth sign unhappy life tape team dust",
    1
  ).then(console.log);
```
output

```
{
   "privateKey":"1352d9efc5c511f89ff262f913e58a2d42649d47246752790cbce6987e100bfe",
   "accounts":[
      {
         "address":"0x26b778f00498df5b730c62b9e706c345cb8e7497",
         "privateKey":"f2e42516a0c80912dccf89481371e6208aa8d009f8c62dde834683cdc766f6f6"
      }
   ]
}
```
Using a different secret (like 'ed25519 seed') you will get: 
```json
{ "privateKey": "0f68ac6f19237d736f33a147ac827a2bc5d86f97932dfb219eab7198623728b9",  ... }
```

What it's not exactly wrong, but to follow ethereum stardards I'm going to copy the class, chaneg the secret and add [Aleksey Popov](https://github.com/alepop) credits. 

```cmd
$ flutter test test/hd_key_test.dart
```
should return a positive result.

Thanks
Allan Clempe

**Comment by zois** [comment]
Thanks very much for looking into this so fast.
But, again the results are different. Probably it has to do with the derivation paths that site is using?
I think it's just a misunderstanding of mine. As I see in your code above, you get the "general" privatekey and from it you derive an address.
Perhaps this is correct. What I am confused is the privatekey and address of the derived addresses. 
So you don't use those in the app? I though that you were getting the 1st address of the derived ones.

Thanks,
Zois

**Comment by allanclempe** [comment]
No, I haven't implemented derived addresses but you can derive many addresses you want from your private key (HdKey.derivePath allows you to do that), the public ones you can use to receive tokens. The private key should never be shared and should live on your device only. Just to keep it simple, the private key you will use to sign transactions and spend tokens. 

[This](https://github.com/allanclempe/ether-wallet-flutter/blob/master/lib/service/contract_service.dart#L28) is the line I'm getting the private key to sign my transaction.

The website you mentioned doesn't show the master private key (from your seed), just the derived ones.

If you use the seed I mentioned above you can see that the first derived private key does match with their algorithm.
seed: 1352d9efc5c511f89ff262f913e58a2d42649d47246752790cbce6987e100bfe
[0] derived private key: f2e42516a0c80912dccf89481371e6208aa8d009f8c62dde834683cdc766f6f6

![image](https://user-images.githubusercontent.com/13680148/82510766-c0a4c680-9b4e-11ea-9e5b-897f8fec699c.png)


Just remember m/44'/0'/0'/0/0 is used for bitcoin addresses, m/44'/60'/0'/0/0 for ETH.

Thanks 
Allan

**Comment by zois** [comment]
Thank you very much! 
Closing this now.

**Comment by zois** [comment]
Re opening this just for a clarification
A. The seed is 'Bitcoin seed' 
B. What should be put in the path string in 
```
KeyData derivePath(String path, String seed) {
```
to get the Ethereum first address? (I have tried many combinations, but can't get the correct one.
My function
```
String getPrivateKeyFromDerivedAddress(String mnemonic) {
    String seed = bip39.mnemonicToSeedHex(mnemonic);
    String path = ""; // what should be put here for Ethereum 1st derived address?
    KeyData master = HDKey.derivePath(path, seed);
    final privateKey = HEX.encode(master.key);
    print("private: $privateKey");
    return privateKey;
  }
```

**Comment by allanclempe** [comment]
Hi Zois, 

You right, I couldn't get it to work using m/44'/60'/0'/0/0 path to derive the address. Libraries written in dart are very limited and I couldn't find any replacement for the one I'm using. The only way to solve that is rewriting HDKey package in dart, which might be a pailful job but would help the community to use more flutter in this space. I would love to help you if you want, but I'm not cryptographer and this might take a while to understand the algorithm and rewrite it properly.

**Comment by allanclempe** [comment]
Just as additional information, HDKey relies on [secp256k1](https://www.npmjs.com/package/secp256k1), a node package that bindings the native [bitcoin-core library](https://github.com/bitcoin-core/secp256k1) written in C. Hence, rewriting the library is not the way to go.

**Comment by zois** [comment]
Hi Allan,

indeed flutter community is a little bit behind in these stuff. However let's not worry about this right now. I was just asking because e.g Metamask, uses the derived addresses and if someone uses the exact 12 words to import in some other wallet, will be confused. 
Thanks very much for looking into this so thoroughly!

Thanks,
Zois

**Comment by MuTe33** [comment]
Hey guys, 

I've encountered the same issue and saw this issue here. Even though this is closed a while ago I come up with a solution. Maybe it will help you if this is still needed. 😄 

I'll post a code snippet here:

```Dart
import 'dart:typed_data';
import 'package:bip32/bip32.dart' as bip32;
import 'package:bip39/bip39.dart' as bip39;
import 'package:hex/hex.dart';

const String mnemonic =  'paddle issue shiver bachelor clarify host educate lawsuit wolf drill discover fresh';

final seed = bip39.mnemonicToSeedHex(mnemonic);

final bip32.BIP32 root = bip32.BIP32.fromSeed(HEX.decode(seed));
final bip32.BIP32 child = root.derivePath("m/44'/60'/0'/0/$childCount"); // <--- this is what you looking for. 0 will give you the first address and then you can iterate.

final privateKey = HEX.encode(child.privateKey);
print('private Key: $privateKey'); //a41823de358c081e2864c49b4f12d2d903fc04a606bd619b7ceb365a6e087e9c

final publicAddress = await addressService.getPublicAddress(privateKey); // some function to derive public key
print('publicAddress: $publicAddress'); // 0xec3705817db92df6f6d8b966c79e3ea61085752b 
```

I've checked with https://iancoleman.io/bip39/ and the addresses are matching :) 

I might create a PR to fix this, if desired. Otherwise feel free to copy paste! 💪 

Hope this helps!

All the best,
MuTe

**Comment by tomi-carrieverse** [comment]
thank you! You're truly a god. The code works very well!!!!
