### ISSUE TITLE
It works well

### ISSUE THREAD

**Issue by rockershead** [allanclempe/ether-wallet-flutter#9]
Hi,
Just want to thank you for your work. The framework you created is awesome to work on. The code works well and I am integrating it into my app as a way to pay tokens(ERC20) over ethereum blockchain, of course with some tweaks.

**Comment by allanclempe** [comment]
I appreciate mate, I'm really glad for helping you and the community in this space.

If you are interested, I'm currently working on a refactor of this project to use hooks to control the components life-cycle and also making components more reusable. Feel free to check out [this branch](https://github.com/allanclempe/ether-wallet-flutter/tree/feature/wallet-using-hooks).

TA

**Comment by rockershead** [comment]
Cool,Awesome. Wiil look at that later. By the way, I did a simple tweak to validate the the amount and address inputted before proceeding with the transaction.

**Comment by allanclempe** [comment]
I haven't spent much time in validations at all. But yes, adapt the way you need to make it better.   I'm going to merge hooks branch into master shortly, but I'll also keep a branch opened with the current version for those who wants to use mobx. 
Thank you again. Closing for now.
